<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
    <div class="left-box-small">
        <h3><?php echo $this->__('Currently Shopping by:') ?></h3>
        <ul>
        <?php foreach ($_filters as $_filter): ?>
            <li>
                <span class="label"><?php echo $this->__($_filter->getName()) ?>:</span> <span class="value"><?php echo $this->stripTags($_filter->getLabel()) ?></span>
                <?php
                    $clearLinkUrl = $_filter->getClearLinkUrl();
                    if ($clearLinkUrl):
                ?>
                    <a class="btn-previous" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Previous') ?>">
                        <?php echo $this->__('Previous') ?>
                    </a>
                    <a class="btn-remove" href="<?php echo $clearLinkUrl ?>" title="<?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>">
                        <?php echo $this->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>
                    </a>
                <?php else: ?>
                    <i><a class="btn-remove" href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>"><?php echo $this->__('Remove This Item') ?></a></i>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
