<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php if($this->canShowBlock()): ?>
<div class="left-box">

    <p class="left-box-title"><?php echo $this->__('Choose by:'); ?></p>

    <?php echo $this->getStateHtml() ?>
    <?php if ($this->getLayer()->getState()->getFilters()): ?>
        <div class="left-box-small">
            <a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a>
        </div>
    <?php endif; ?>
    <?php if($this->canShowOptions()): ?>
        <?php $_filters = $this->getFilters() ?>
        <?php foreach ($_filters as $_filter): ?>
            <?php if($_filter->getItemsCount()): ?>
                <div class="left-box-small">
                    <h3><?php echo $this->__($_filter->getName()) ?></h3>
                    <?php echo $_filter->getHtml() ?>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        <script type="text/javascript">decorateDataList('narrow-by-list')</script>
    <?php endif; ?>
</div>
<?php endif; ?>
