<?php
    $attributes = array();

    $_product = $this->getProduct();
    $parentIds = Mage::getResourceSingleton('catalog/product_type_configurable')->getParentIdsByChild($_product->getId());
    if($parentIds)
    {
        $_parentProduct = Mage::getModel('catalog/product')->load($parentIds[0]);
        $attributes = $_parentProduct->getTypeInstance(true)->getConfigurableAttributesAsArray($_parentProduct);

//         $childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null, $_parentProduct);
//         foreach($childProducts as $child)
//         {
//             echo $child->getName().'<br />';
//         }
    }
?>
<?php if($attributes) : ?>
    <?php foreach($attributes as $item) : ?>
        <tr>
            <td class="product-tab"><?php echo $item['label']; ?></td>
            <td class="product-select">
                <?php $currentValue = $_product->getData($item['attribute_code']); ?>
                <select name="<?php echo $item['attribute_code']; ?>">
                    <?php foreach($item['values'] as $value) : ?>
                        <?php $selected = ( $value['value_index'] == $currentValue ? 'selected="selected"' : '' ); ?>
                        <option value="<?php echo $value['value_index']; ?>" <?php echo $selected; ?>>
                            <?php echo $value['store_label']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>