<?php
/**
 * Partial template of product form - configurable products attributes
 *
 * @see Mage_Catalog_Block_Product_Attributes
 */
?>
<?php
    $_product = $this->getProduct();
    $attributes = $this->getConfigurableAttributes();
?>
<?php if($attributes) : ?>
    <?php foreach($attributes as $item) : ?>
        <tr>
            <td class="product-tab"><?php echo $item['label']; ?></td>
            <td class="product-select">
                <?php $currentValue = $_product->getData($item['attribute_code']); ?>
                <select name="<?php echo $item['attribute_code']; ?>">
                    <?php foreach($item['values'] as $value) : ?>
                        <?php $selected = ( $value['value_index'] == $currentValue ? 'selected="selected"' : '' ); ?>
                        <option value="<?php echo $value['value_index']; ?>" <?php echo $selected; ?>>
                            <?php echo $value['store_label']; ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>