<?php
    $_helper = $this->helper('catalog/output');
    $_coreHelper = $this->helper('core');
    $_product = $this->getProduct();
?>
<?php if($_crossSellProducts = $_product->getCrossSellProducts()) : ?>

    <div id="buy-more">
        <h3><?php echo $this->__('Or how about ...'); ?></h3>

        <?php foreach ($_crossSellProducts as $_item): ?>
            <?php $_item = Mage::getModel('catalog/product')->load($_item->getId()); ?>
            <div class="buy-more-box">
                <a href="<?php echo $_item->getProductUrl(); ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($_item, 'image')->resize(160, 160); ?>" alt="" />
                </a>
                <p class="buy-more-title">
                    <a href="<?php echo $_item->getProductUrl(); ?>"><?php echo $this->htmlEscape($_item->getName()); ?></a>
                </p>
                <p class="buy-more-description">
                    <?php echo $_helper->productAttribute($_item, nl2br($_item->getDescription()), 'description'); ?>
                </p>
                <?php if($_item->getSpecialPrice()) : ?>
                    <p class="buy-more-price products-category-price-discound"><?php echo $_coreHelper->formatPrice($_item->getPrice()); ?></p>
                    <p class="buy-more-special-price">
                        <?php echo $this->__('Special Price:') . ' ' . $_coreHelper->formatPrice($_item->getSpecialPrice()); ?>
                    </p>
                <?php else : ?>
                    <p class="buy-more-price"><?php echo $_coreHelper->formatPrice($_item->getPrice()); ?></p>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>

        <div class="clr"></div>
    </div><!--buy-more-->

<?php endif; ?>