<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();

    $tabs = array(
        array(
            'key' => 'description',
            'name' => 'We Say...',
        ),
        array(
            'key' => 'product_details',
            'name' => 'Product Details',
        ),
        array(
            'key' => 'sizing_information',
            'name' => 'Sizing Information',
        ),
        array(
            'key' => 'delivery_and_returns',
            'name' => 'Delivery &amp; Returns',
        ),
    );
?>
<div id="product-details">

    <ul id="product-details-menu">
        <?php foreach($tabs as $index => $tab) : ?>
            <li id="product-details-button<?php echo $index; ?>" mage-tab="<?php echo $index; ?>">
                <a href="#"><?php echo $this->__($tab['name']); ?></a>
            </li>
        <?php endforeach; ?>
    </ul>

    <?php foreach($tabs as $index => $tab) : ?>
        <div id="product-details-tab<?php echo $index; ?>" class="product-details-tab">
            <?php echo $_helper->productAttribute($_product, nl2br($_product->getData($tab['key'])), $tab['key']); ?>
        </div>
    <?php endforeach; ?>

    <script type="text/javascript">initDetailsTabs();</script>

    <div class="clr"></div>

</div><!--product details-->