<?php $_product = $this->getProduct(); ?>
<span class="product-extra-menu">
    <?php if ($this->canEmailToFriend()): ?>
        <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Tell a friend') ?></a> |
    <?php endif; ?>

    <?php $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product); ?>
    <?php if($_compareUrl) : ?>
        <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a> |
    <?php endif; ?>

    <?php if ($this->helper('wishlist')->isAllow()) : ?>
        <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
    <?php endif; ?>
</span>