<?php
    $_helper = $this->helper('catalog/output');
    $_coreHelper = $this->helper('core');
    $_product = $this->getProduct();

    $parentIds = Mage::getResourceSingleton('catalog/product_type_configurable')->getParentIdsByChild($_product->getId());
    if($parentIds)
    {
        $_parentProduct = Mage::getModel('catalog/product')->load($parentIds[0]);

        $attributeOptions = array();
        $productAttributeOptions = $_parentProduct->getTypeInstance(true)->getConfigurableAttributesAsArray($_parentProduct);
        foreach ($productAttributeOptions as $productAttribute)
        {
            foreach ($productAttribute['values'] as $attribute)
            {
                $attributeOptions[$productAttribute['label']][$attribute['value_index']] = $attribute['store_label'];
            }
        }
    }
?>
<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

    <table>
        <?php if($attributeOptions) : ?>
            <?php foreach($attributeOptions as $key => $values) : ?>
                <tr>
                    <td class="product-tab"><?php echo $key; ?></td>
                    <td class="product-select">
                        <?php
                            $attribute = Mage::getModel('eav/config')->getAttribute('catalog_product', $key);
                            $currentValue = $_product->getData(strtolower($key));
                        ?>
                        <select>
                            <?php foreach($values as $value => $label) : ?>
                                <?php //$_product = Mage::getModel('catalog/product')->loadByAttribute($key, $value); ?>
                                <?php $selected = $value == $currentValue ? 'selected="selected"' : ''; ?>
                                <option value="<?php echo $value; ?>" <?php echo $selected; ?>><?php echo $label; ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
        <tr>
            <td class="product-tab"><?php echo $this->__('Quantity'); ?></td>
            <td class="product-number">
                <input type="text" id="qty" name="qty" value="<?php echo $this->getProductDefaultQty() * 1 ?>" class="input-text qty" />
                <span class="product-availability">Availability: <?php echo $_product->getStockItem()->getQty() > 0 ? 'In stock' : 'Unavailable' ?></span>
            </td>
        </tr>
        <tr>
            <td class="product-tab"><?php echo $this->__('Price'); ?></td>
            <td class="product-price">
                <?php
                    $productPrice = $_product->getSpecialPrice() ? $_product->getSpecialPrice() : $_product->getPrice();
                    echo $_coreHelper->formatPrice($productPrice);
                ?>
            </td>
        </tr>
    </table>

    <div class="product-add">
        <?php if($_product->isSaleable()): ?>
            <button type="submit" class="button"><?php echo $this->__('Add to Basket'); ?></button>
        <?php endif; ?>

        <span class="product-extra-menu">
            <?php if ($this->canEmailToFriend()): ?>
                <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Tell a friend') ?></a> |
            <?php endif; ?>

            <?php $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product); ?>
            <?php if($_compareUrl) : ?>
                <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a> |
            <?php endif; ?>

            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
            <?php endif; ?>
        </span>
    </div>

</form>
