<?php
    $_product = $this->getProduct();
?>
<form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

    <table>
        <?php echo $this->getChildHtml('attributes'); ?>
        <tr>
            <td class="product-tab"><?php echo $this->__('Quantity'); ?></td>
            <td class="product-number">
                <input type="text" id="qty" name="qty" value="<?php echo $this->getProductDefaultQty() * 1 ?>" class="input-text qty" />
                <span class="product-availability">Availability: <?php echo $_product->getStockItem()->getQty() > 0 ? 'In stock' : 'Unavailable' ?></span>
            </td>
        </tr>
        <tr>
            <td class="product-tab"><?php echo $this->__('Price'); ?></td>
            <td class="product-price">
                <?php
                    $productPrice = $_product->getSpecialPrice() ? $_product->getSpecialPrice() : $_product->getPrice();
                    echo $this->helper('core')->formatPrice($productPrice);
                ?>
            </td>
        </tr>
    </table>

    <div class="product-add">
        <?php if($_product->isSaleable()): ?>
            <button type="submit" class="button"><?php echo $this->__('Add to Basket'); ?></button>
        <?php endif; ?>

        <?php echo $this->getChildHtml('extra'); ?>
    </div>

</form>