<?php $_product = $this->getProduct(); ?>
<?php foreach ($_product->getMediaGalleryImages() as $_image): ?>
    <a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>">
        <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="64" height="63" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" />
    </a>
<?php endforeach; ?>