<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl())
    {
        $_imgHtml = '<div id="comercial-baner"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></div>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($_imgUrl): ?>
    <?php echo $_imgHtml ?>
<?php endif; ?>

<div id="comecial-description">
    <div id="comecial-description-left">
        <h3>Wchich Duvet?</h3>
        <p>Lorem ipsum delor et consecticit nonummy et salal.</p>
        <a href="#">Find out more ›</a>
    </div><!--comecial-description-left-->

    <div id="comecial-description-right">
        <h3>Wchich is Best?</h3>
        <p>Lorem ipsum delor et consecticit nonummy et salal.</p>
        <a href="#">Find out more ›</a>
    </div><!--comecial-description-right-->

    <div class="clr"></div>
</div>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div id="products-category-bottom-description">
        <p><?php echo nl2br($_helper->categoryAttribute($_category, $_description, 'description')); ?></p>
    </div>
<?php endif; ?>