<?php
/**
 * Category left navigation
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php
    $read = Mage::getSingleton("core/resource")->getConnection("core_read");
    $select = $read->select()->from(array("a" => "eav_attribute"), array("attribute_code", "frontend_label"))
            ->join(array("ao" => "eav_attribute_option"), "a.attribute_id = ao.attribute_id", array())
            ->order("frontend_label");

    $attributes = $read->fetchPairs($select);

    $attributeOptions = array();
    foreach($attributes as $key => $name)
    {
        $attributeInfo = Mage::getResourceModel('eav/entity_attribute_collection')->setCodeFilter($key)->getFirstItem();
        $attributeOptions[$key] = $attributeInfo->getSource()->getAllOptions(false);

    }
//     echo "<pre>"; print_r($attributeOptions); echo "</pre>";
?>
<div class="left-box">

    <p class="left-box-title">Choose by:</p>

    <?php foreach($attributeOptions as $key => $values) : ?>
        <div class="left-box-small">
            <h3><?php echo $attributes[$key]; ?></h3>
            <ul>
                <?php foreach($values as $value) : ?>
                    <li><a href="<?php echo '...'; ?>"><?php echo $value['label']; ?></a></li>
                <?php endforeach; ?>
            </ul>
        </div><!--left-box-small-->
    <?php endforeach; ?>

</div><!--left-box-->
