<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
    <div class="left-box recently-view">
        <p class="left-box-title"><?php echo $this->__('Recently Viewed Items') ?></p>

        <ul>
            <?php foreach ($_products as $_item): ?>
                <li class="item">
                    <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>">
                        <img alt="" src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(67, 67); ?>" />
                        <?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?>
                    </a></p>
                </li>
            <?php endforeach; ?>
        </ul>

        <div class="clr"></div>
    </div><!--left-box-->
<?php endif; ?>
