<?php
    $_product = $this->getProduct();

    if($_product->getTypeId() == 'configurable')
    {
        $_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
    }
    else
    {
        $_attributes = array();
    }
?>
<pre><?php print_r($_tierPrices); ?></pre>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <?php foreach($_attributes as $_attribute): ?>
        <tr>
            <td class="product-tab"><?php echo $_attribute->getLabel() ?></td>
            <td class="product-select">
                <select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
                    <option><?php echo $this->__('Choose an Option...') ?></option>
                </select>
            </td>
        </tr>
    <?php endforeach; ?>

    <script type="text/javascript">
        var spConfig = new Product.Config(<?php echo $this->getJsonConfig() ?>);
    </script>
<?php endif;?>
