<?php
    $_coreHelper = $this->helper('core');
    $_products = $this->getProductCollection();
    if ($_products && $_products->getSize()):
?>

<script type="text/javascript">
$(document).ready(function() {
	try {
    	var oHandlerHorizontal = $("#carouseldiv").msCarousel({boxClass:'div.set', width:907, height:302, scrollSpeed:500}).data("msCarousel");
    	$("#next").click(function() {
    		oHandlerHorizontal.next();
    	});
    	$("#previous").click(function() {
    		oHandlerHorizontal.previous();
    	});
	} catch(e) {
    	alert(e.message);
	}
})
</script>

<div id="box-slide-offer">

    <h2 class="box-title">Our Bestsellers</h2>

    <div class="previous-btn">
        <button name="previous" id="previous" type="button"><img alt="" src="<?php echo $this->getSkinUrl(); ?>images/prev-btn.jpg" /></button>
    </div>

    <div class="next-btn">
        <button name="next" id="next" type="button"><img alt="" src="<?php echo $this->getSkinUrl(); ?>images/next-btn.jpg" /></button>
    </div>

    <div id="carouseldiv">
        <?php foreach ($_products->getItems() as $_product): ?>
            <div class="set box-slide-product">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                    <img alt="" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(160, 160); ?>" />
                </a>
                <h3 class="slider-product-title"><?php echo $this->htmlEscape($_product->getName()) ?></h3>
                <p class="box-slide-description"><?php echo $_product->getShortDescription(); ?></p>

                <?php if($_product->getSpecialPrice()) : ?>
                    <p class="box-slide-price box-slide-price-discound">From <?php echo $_coreHelper->formatPrice($_product->getPrice()); ?></p>
                    <p class="box-slide-special-price">Special Price: <?php echo $_coreHelper->formatPrice($_product->getSpecialPrice()); ?></p>
                <?php else : ?>
                    <p class="box-slide-price">From <?php echo $_coreHelper->formatPrice($_product->getPrice()); ?></p>
                <?php endif; ?>
            </div>
        <?php endforeach; ?>

        <div class="clr"></div>
    </div>

</div><!-- box-slide-offer -->

<?php else: ?>
<p>no bestsellers found</p>
<?php endif; ?>