<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $_coreHelper = $this->helper('core');
?>
<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div id="products-category">
    <?php echo $this->getToolbarHtml() ?>

    <?php foreach ($_productCollection as $_product): ?>
        <div class="products-category-box">
            <a href="<?php echo $_product->getProductUrl() ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(161); ?>" width="161" height="161" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" />
                <h3 class="products-category-title"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></h3>
            </a>
            <p class="products-category-description"><?php echo $_product->getShortDescription(); ?></p>
            <?php if($_product->getSpecialPrice()) : ?>
                <p class="products-category-price products-category-price-discound">From <?php echo $_coreHelper->formatPrice($_product->getPrice()); ?></p>
                <p class="products-category-special-price">Special Price: <?php echo $_coreHelper->formatPrice($_product->getSpecialPrice()); ?></p>
            <?php else : ?>
                <p class="products-category-price">From <?php echo $_coreHelper->formatPrice($_product->getPrice()); ?></p>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>

    <div class="clr"></div>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
