<div id="baner">
    <div id="slider" class="nivoSlider">
        <img src="<?php echo $this->getSkinUrl(); ?>images/slide-1.jpg" alt="" />
        <img src="<?php echo $this->getSkinUrl(); ?>images/slide-2.jpg" alt="" />
        <img src="<?php echo $this->getSkinUrl(); ?>images/slide-3.jpg" alt="" />
        <img src="<?php echo $this->getSkinUrl(); ?>images/slide-4.jpg" alt="" />
    </div>
</div><!--baner-->

<div id="box-3-offer">
	<div class="box-3-offer-column"><img src="<?php echo $this->getSkinUrl(); ?>images/box3-1.jpg" alt="" /></div><!--box-3-offer-->
	<div class="box-3-offer-column"><img src="<?php echo $this->getSkinUrl(); ?>images/box3-2.jpg" alt="" /></div><!--box-3-offer-->
	<div class="box-3-offer-column box-3-offer-last"><img src="<?php echo $this->getSkinUrl(); ?>images/box3-3.jpg" alt="" /></div><!--box-3-offer-->
    <div class="clr"></div>
</div><!--box-3-offer-->