<?php
    $sliderLimit = 3;
    $_products = $this->getProductCollection();
    if ($_products && $_products->getSize()) :
?>
    <div id="baner">
        <div id="slider" class="nivoSlider">
            <?php foreach ($_products->getItems() as $_product): ?>
                <img alt="" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(976, 349); ?>" />
            <?php endforeach; ?>
        </div>
    </div><!--baner-->

    <div id="box-3-offer">
        <?php foreach ($_products->getItems() as $_product): ?>
            <?php $sliderLimit -= 1; ?>

            <div class="box-3-offer-column<?php if($sliderLimit == 0) { echo ' box-3-offer-last'; } ?>">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(320, 161); ?>" alt="" />
            </div><!--box-3-offer-->

            <?php if($sliderLimit <= 0) { break; } ?>
        <?php endforeach; ?>

        <div class="clr"></div>
    </div><!--box-3-offer-->
<?php endif; ?>