<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div id="single-left">
        <div id="thumb-left">
            <?php foreach ($_product->getMediaGalleryImages() as $_image): ?>
                <a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" title="<?php echo $this->escapeHtml($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="64" height="63" alt="<?php echo $this->escapeHtml($_image->getLabel()) ?>" /></a>
            <?php endforeach; ?>
        </div><!--thumb-left-->

        <div id="single-thumb-right">

            <div id="single-thumb-right-foto">
                <?php
                    $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
                    echo $_helper->productAttribute($_product, $_img, 'image');
                ?>
                <p class="single-description">Click image to view larger picture</p>
            </div><!--single-thumb-right-foto-->

            <div class="perfect-with">

                <h3>Goes perfectly with:</h3>

                <div class="perfect-with-img">
                    <img alt="" src="products/p1.jpg" />
                    <p class="perfect-with-desc">Mulberry Silk Pillows</p>
                    <p class="perfect-with-price">&pound;65.00</p>
                </div>

                <div class="perfect-with-img">
                    <img alt="" src="products/p2.jpg" />
                    <p class="perfect-with-desc">Mulberry Silk Pillows</p>
                    <p class="perfect-with-price">&pound;65.00</p>
                </div>

                <div class="perfect-with-img">
                    <img alt="" src="products/p3.jpg" />
                    <p class="perfect-with-desc">Mulberry Silk Pillows</p>
                    <p class="perfect-with-price perfect-with-discount">&pound;65.00</p>
                    <p class="perfect-with-price-sale">Special Price: &pound;45.00</p>
                </div>

                <div class="clr"></div>
            </div><!--perfect with-->

        </div><!--single-thumb-right-->

        <div class="clr"></div>
</div>

<div id="single-right">

    <h2><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
    <p class="single-p-desc"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></p>

    <div id="single-product-information">
        <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>

            <table>
                <tr>
                    <td class="product-tab">Size</td>
                    <td class="product-select">
                        <select>
                            <option value="double">Double</option>
                            <option value="single">Single</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="product-tab">Warmth</td>
                    <td class="product-select">
                        <select>
                            <option value="summer">Summer 4.5 tog</option>
                            <option value="summer-2">Summer 5.0 tog</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="product-tab">Quantity</td>
                    <td class="product-number">
                        <input type="text" id="qty" name="qty" value="<?php echo $this->getProductDefaultQty() * 1 ?>" class="input-text qty" />
                        <span class="product-availability">Availability: <?php echo $_product->getStockItem()->getQty() > 0 ? 'In stock' : 'Unavailable' ?></span>
                    </td>
                </tr>
                <tr>
                    <td class="product-tab">Price</td>
                    <td class="product-price">
                        <?php
                            $productPrice = $_product->getSpecialPrice() ? $_product->getSpecialPrice() : $_product->getPrice();
                            echo $this->helper('core')->formatPrice($productPrice);
                        ?>
                    </td>
                </tr>
            </table>

            <div class="product-add">
                <?php if($_product->isSaleable()): ?>
                    <button type="submit" class="button"><?php echo $this->__('Add to Basket'); ?></button>
                <?php endif; ?>

                <span class="product-extra-menu">
                    <?php if ($this->canEmailToFriend()): ?>
                        <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Tell a friend') ?></a> |
                    <?php endif; ?>

                    <?php $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product); ?>
                    <?php if($_compareUrl) : ?>
                        <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a> |
                    <?php endif; ?>

                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                        <a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                    <?php endif; ?>
                </span>
            </div>

        </form>

        <div id="product-details">

            <ul id="product-details-menu">
                <li mage-tab="1" class="product-details-menu-current"><a href="#">We Say...</a></li>
                <li mage-tab="2"><a href="#">Product Details</a></li>
                <li mage-tab="3"><a href="#">Sizing Information</a></li>
                <li mage-tab="4" id="product-details-menu-last"><a href="#">Delivery &amp; Returns</a></li>
            </ul>

            <div id="product-details-tab1" class="product-details-tab">
                <?php echo $_helper->productAttribute($_product, nl2br($_product->getDescription()), 'description') ?>
            </div><!--product-details-tab1-->

            <div id="product-details-tab2" class="product-details-tab">
                tab 2
            </div><!--product-details-tab2-->

            <div id="product-details-tab3" class="product-details-tab">
                tab 3
            </div><!--product-details-tab3-->

            <div id="product-details-tab4" class="product-details-tab">
                tab 4
            </div><!--product-details-tab4-->

            <script type="text/javascript">
                $('.product-details-tab').hide();
                $('#product-details-tab-1').show();

                $('#product-details-menu').children().click(function(){
                    $('.product-details-menu-current').removeClass('product-details-menu-current');
                    $(this).addClass('product-details-menu-current');

                    var id = '#product-details-tab' + $(this).attr('mage-tab');
                    $('.product-details-tab').hide();
                    $(id).show();
                });
            </script>

            <div class="clr"></div>

        </div><!--product details-->

    </div><!--single product information-->

</div><!--right-->

<div class="clr"></div>

<div id="customers-help">

    <div class="customers-reviews">
        <h3>Customers Review</h3>
        <div class="customres-box">
            <p class="customres-box-big">
                <?php echo $this->__('Write Your Own Review about') . ' ' . $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
            </p>
            <p class="customres-box-small"><?php echo $this->__('Only registered users can write reviews. Please log in or register'); ?></p>
        </div>
    </div><!--customers review-->

    <div class="need-help">
        <h3><?php echo $this->__('Need Help Deciding?'); ?></h3>
        <ul>
            <li><a href="#"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') . $this->__('Reviews'); ?></a></li>
            <li><a href="#"><?php echo $this->__('Which Duvet do I choose?'); ?></a></li>
            <li><a href="#"><?php echo $this->__('Continental Pillows'); ?></a></li>
        </ul>

    </div><!--need help-->

</div><!--customer-help-->

<div class="clr"></div>

<div id="buy-more">

    <h3>Or how about ...</h3>

    <div class="buy-more-box">
        <img alt="" src="products/by1.jpg" />
        <p class="buy-more-title">Blue Stripe Duvet Set &amp; Pillows</p>
        <p class="buy-more-description">Hypoallergenic &amp; Cotton Cover Medium-weight Hollowfibre</p>
        <p class="buy-more-price products-category-price-discound">From &pound;65.00</p>
        <p class="buy-more-special-price">Special Price: &pound;45.00</p>
    </div>

    <div class="buy-more-box">
        <img alt="" src="products/by2.jpg" />
        <p class="buy-more-title">Navy Blue Gingham Duvet</p>
        <p class="buy-more-description">Hypoallergenic &amp; Cotton Cover Medium-weight Hollowfibre</p>
        <p class="buy-more-price products-category-price-discound">From &pound;65.00</p>
    </div>

    <div class="buy-more-box">
        <img alt="" src="products/by3.jpg" />
        <p class="buy-more-title">Blue Stripe Duvet Set &amp; Pillows</p>
        <p class="buy-more-description">Hypoallergenic &amp; Cotton Cover Medium-weight Hollowfibre</p>
        <p class="buy-more-price products-category-price-discound">From &pound;65.00</p>
        <p class="buy-more-special-price">Special Price: &pound;45.00</p>
    </div>

    <div class="buy-more-box">
        <img alt="" src="products/by4.jpg" />
        <p class="buy-more-title">Navy Blue Gingham Duvet</p>
        <p class="buy-more-description">Hypoallergenic &amp; Cotton Cover Medium-weight Hollowfibre</p>
        <p class="buy-more-price products-category-price-discound">From &pound;65.00</p>
    </div>

    <div class="clr"></div>

</div><!--buy-more-->
