<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml(); ?></div>

<div id="single-left">
    <div id="thumb-left">
        <?php echo $this->getChildHtml('media'); ?>
    </div><!--thumb-left-->

    <div id="single-thumb-right">

        <div id="single-thumb-right-foto">
            <?php
                $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(265).'" alt="'.$this->escapeHtml($this->getImageLabel()).'" title="'.$this->escapeHtml($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
            <p class="single-description"><?php echo $this->__('Click image to view larger picture'); ?></p>
        </div><!--single-thumb-right-foto-->

        <?php echo $this->getChildHtml('related'); ?>

    </div><!--single-thumb-right-->

    <div class="clr"></div>
</div><!--single-left-->

<div id="single-right">
    <h2><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h2>
    <p class="single-p-desc"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></p>

    <div id="single-product-information">
        <?php echo $this->getChildHtml('form'); ?>
        <?php echo $this->getChildHtml('details'); ?>
    </div><!--single product information-->
</div><!--single-right-->

<div class="clr"></div>

<?php echo $this->getChildHtml('product_additional_data'); ?>
<?php echo $this->getChildHtml('customers-review'); ?>
<?php echo $this->getChildHtml('crosssell'); ?>