<?php
/**
 * Template for Mage_Page_Block_Html
 */

    function isHomeOrCatalog()
    {
        if(Mage::getBlockSingleton('page/html_header')->getIsHomePage())
        {
            return true;
        }

        $routeName = Mage::app()->getRequest()->getRouteName();
        if($routeName == 'catalog' && Mage::registry('current_category'))
        {
            return true;
        }

        return false;
    }

?><!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div id="wrapper-content">
    <?php echo $this->getChildHtml('global_messages') ?>
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <?php echo $this->getChildHtml('breadcrumbs') ?>
        <div class="main-container col2-right-layout">
            <div class="main">
                <div class="<?php echo isHomeOrCatalog() ? '' : 'col-main'; ?>">
                    <?php echo $this->getChildHtml('content') ?>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>