<?php echo $this->getChildHtml('newsletter'); ?>

<div id="bottom-links">

    <div id="bottom-left">

        <div class="bottom-column-left column-one">
            <?php echo Mage::getModel('core/variable')->loadByCode('contact-info')->getValue('html'); ?>
        </div><!--bottom-column-left-->

        <div class="bottom-column-right column-two">
            <?php echo $this->getChildHtml('my_footer_block_left'); ?>
        </div><!--bottom-column-right-->

        <div class="clr"></div>

        <div id="payment">
            <img alt="" src="<?php echo $this->getSkinUrl(); ?>images/payment.jpg" />
        </div><!--payment-->

    </div><!--bottom left-->

    <div id="bottom-right">
        <?php echo $this->getChildHtml('my_footer_block_right'); ?>
        <div class="clr"></div>
    </div><!--bottom right-->

    <div class="clr"></div>

</div><!--bottom links-->

<div id="footer">
    <p><?php echo nl2br($this->getCopyright()); ?></p>
</div><!--footer-->