<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="header-container">
    <div class="header">
        <h1 class="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <div class="quick-access">
            <?php $this->getChild('topLinks')->setData('className', 'links'); ?>
            <?php echo $this->getChildHtml('topLinks') ?>
            <?php echo $this->getChildHtml('topSearch') ?>
            <div id="checkout-button">
                <a href="<?php echo $this->getUrl('checkout'); ?>">Checkout</a>
            </div>
        </div>
        <?php echo $this->getChildHtml('topContainer'); ?>
        <div class="clr"></div>
    </div>
</div>
<?php echo $this->getChildHtml('topMenu') ?>